@echo off
packwiz modrinth add appleskin 
packwiz modrinth add architectury-api 
packwiz modrinth add badoptimizations 
packwiz modrinth add better-mount-hud 
packwiz modrinth add boat-item-view 
packwiz modrinth add calcmod 
packwiz modrinth add chat-heads 
packwiz modrinth add cloth-config 
packwiz modrinth add continuity 
packwiz modrinth add crash-assistant 
packwiz modrinth add cull-leaves 
packwiz modrinth add debugify 
packwiz modrinth add distanthorizons 
packwiz modrinth add dynamic-fps 
packwiz modrinth add e4mc 
packwiz modrinth add entity-model-features 
packwiz modrinth add entitytexturefeatures 
packwiz modrinth add entityculling 
packwiz modrinth add entity-view-distance 
packwiz modrinth add fabric-api 
packwiz modrinth add fabric-language-kotlin 
packwiz modrinth add fast-ip-ping 
packwiz modrinth add ferrite-core 
packwiz modrinth add fpsdisplay 
packwiz modrinth add gputape 
packwiz modrinth add held-item-info 
packwiz modrinth add immediatelyfast 
packwiz modrinth add iris 
packwiz modrinth add lambdynamiclights 
packwiz modrinth add language-reload 
packwiz modrinth add lazy-language-loader 
packwiz modrinth add libjf 
packwiz modrinth add lithium 
packwiz modrinth add midnightlib 
packwiz modrinth add mixintrace 
packwiz modrinth add modelfix 
packwiz modrinth add modernfix 
packwiz modrinth add modmenu 
packwiz modrinth add morechathistory 
packwiz modrinth add moreculling 
packwiz modrinth add no-chat-reports 
packwiz modrinth add not-enough-animations 
packwiz modrinth add optigui 
packwiz modrinth add puzzle 
packwiz modrinth add reeses-sodium-options 
packwiz modrinth add replaymod 
packwiz modrinth add server-resource-pack-checker 
packwiz modrinth add rei 
packwiz modrinth add shulkerboxtooltip 
packwiz modrinth add sodium-extra 
packwiz modrinth add sodium-extra-information 
packwiz modrinth add sodium 
packwiz modrinth add super-fast-math 
packwiz modrinth add viafabricplus 
packwiz modrinth add wavey-capes 
packwiz modrinth add xaeros-minimap 
packwiz modrinth add xaeros-world-map 
packwiz modrinth add yacl 
packwiz modrinth add zoomify 
packwiz modrinth add vmp-fabric 
packwiz modrinth add noisium 
packwiz modrinth add better-beds 
packwiz modrinth add skip-transitions 
packwiz modrinth add renderscale 
packwiz modrinth add particle-core 
packwiz modrinth add fast-items 
packwiz modrinth add controlify 
packwiz modrinth add ebe 
packwiz modrinth add noxesium 
packwiz modrinth add smooth-scroll 
packwiz modrinth add sodium-options-mod-compat 
packwiz modrinth add mpalladium 
packwiz modrinth add nodynamicfps 
packwiz modrinth add toadlib 
packwiz modrinth add fzzy-config 
packwiz modrinth add txnilib 
packwiz modrinth add sodium-options-api 
packwiz modrinth add cool-elytra-roll 
packwiz modrinth add variants-cit 
packwiz modrinth add placeholder-api 
packwiz modrinth add anvians-lib 
packwiz modrinth add forge-config-api-port 
pause
